### ISSUE TITLE
Pico micro-ROS life cycle and multiple agent reconnects

### ISSUE THREAD

**Issue by monkeyiq** [micro-ROS/micro_ros_raspberrypi_pico_sdk#666]
- Hardware description: Pico
- RTOS: libmicroros/libmicroros.a & pico_sdk. Basically micro_ros_raspberrypi_pico_sdk example
- Installation type: fairly close to git clone setup
- Version or commit hash: Humble, a431b36647ec9234d1abca0f61afd2b3118761b5

Expected / Actual allowing microros/micro-ros-agent:humble serial to reconnect over serial after it was stopped.

Hi,

  I have been tinkering with micro-ROS and the raspberry PI Pico. The session management part of this seems to have a little learning curve. My testing for this is Pico based using serial comms to the host PC running the agent. The transport is as in the example pico_micro_ros_example.c file [2]. From my initial testing if one leaves the publishers and subscribers running and the agent is stopped and restarted then the agent does not discover what the microcontroller is doing. Given some of the delays I see in fini() it is possible that I did not wait long enough for this to stabilize. One might see the following

```
$ docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:humble serial --dev /dev/ttyACM0 -b 921600  -v4
[1664174623.445190] info     | TermiosAgentLinux.cpp | init                     | Serial port not found. | device: /dev/ttyACM0, error 2, waiting for connection...
[1664174624.453475] info     | TermiosAgentLinux.cpp | init                     | Serial port not found. | device: /dev/ttyACM0, error 2, waiting for connection...
[1664174625.461379] info     | TermiosAgentLinux.cpp | init                     | Serial port not found. | device: /dev/ttyACM0, error 2, waiting for connection...
[1664174626.220771] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3
[1664174626.222100] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 4
[1664174626.822893] info     | Root.cpp           | create_client            | create                 | client_key: 0x3ACDB8DD, session_id: 0x81
[1664174626.823052] info     | SessionManager.hpp | establish_session        | session established    | client_key: 0x3ACDB8DD, address: 0
[1664174626.896533] info     | ProxyClient.cpp    | create_participant       | participant created    | client_key: 0x3ACDB8DD, participant_id: 0x000(1)
[1664174626.901868] info     | ProxyClient.cpp    | create_topic             | topic created          | client_key: 0x3ACDB8DD, topic_id: 0x000(2), participant_id: 0x000(1)
[1664174626.905210] info     | ProxyClient.cpp    | create_publisher         | publisher created      | client_key: 0x3ACDB8DD, publisher_id: 0x000(3), participant_id: 0x000(1)
[1664174626.909072] info     | ProxyClient.cpp    | create_datawriter        | datawriter created     | client_key: 0x3ACDB8DD, datawriter_id: 0x000(5), publisher_id: 0x000(3)
^C[ros2run]: Interrupt

$ docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:humble serial --dev /dev/ttyACM0 -b 921600  -v4
[1664174633.987422] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3
[1664174633.987604] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 4
... wait forever and no create_client ...
```

  It seems from examples like the micro-ros_reconnection_example [1] that the micro controller code should determine if the agent is live, for example doing a ping to the agent over serial to try to figure out if the agent is still around or has gone away for some reason. If the agent can not be contacted then the session should be cleaned up using the fini() calls and remade once an agent reconnects.

  Calling the fini() calls can take a long time, setting RMW_UXRCE_ENTITY_DESTROY_TIMEOUT very low helps a bit here, resulting in a session teardown of around 10 seconds. Normally this may be 30 seconds for the same code. 

  To avoid using constant rmw_uros_ping_agent() pings I also have code to use a subscriber on the robot heartbeat topic (a synthetic signal published by my robot PC once a second). A once per second timer is used to trigger a disconnect if the heartbeat received on the Pico is n seconds or more old. My designs generally call for a once per second timer to publish data from the micro controller so the timer callback can be shared and the overall cost is a single subscriber to monitor the heartbeat topic.

 I am wondering if this rmw_uros_ping_agent() or heartbeat/timer is the intended way to use a Pico with micro-ROS over serial or if I have missed some key examples or docs. Perhaps asking publicly will also help future robot travellers in their research.

I notice here if I do not run the heartbeat publisher and let the Pico think it should do all the fini() calls then it will be fast
while the agent is actually available. If the agent is control-c closed first then it will take about 10 seconds for the fini() calls
as they can not reach the agent. If you are doing your own session is alive checking is there a way to close the connection in a manner that has less delay when the agent is indeed not available?

  If this is the intended life cycle I might work on an example similar to pico_micro_ros_example.c with reconnect for possible inclusion into the repo.

[1] https://github.com/micro-ROS/micro_ros_arduino/blob/humble/examples/micro-ros_reconnection_example/micro-ros_reconnection_example.ino
[2] https://github.com/micro-ROS/micro_ros_raspberrypi_pico_sdk/blob/humble/pico_micro_ros_example.c

**Comment by monkeyiq** [comment]
I assume these go into respective locations in microros_static_library/library_generation/colcon.meta
```
...
        "microxrcedds_client": {
            "cmake-args": [
...
                "-DUCLIENT_MAX_SESSION_CONNECTION_ATTEMPTS=3",
...
            ]
        },
        "rmw_microxrcedds": {
            "cmake-args": [
...
                "-DRMW_UXRCE_ENTITY_CREATION_DESTROY_TIMEOUT=0"
```

I have also tried adding them to CMakeLists.txt though it might be the above is the only needed update.
```
SET(CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} -ffunction-sections -fdata-sections -DUCLIENT_MAX_SESSION_CONNECTION_ATTEMPTS=3 -DRMW_UXRCE_ENTITY_CREATION_DESTROY_TIMEOUT=0")
SET(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -ffunction-sections -fdata-sections  -DUCLIENT_MAX_SESSION_CONNECTION_ATTEMPTS=3 -DRMW_UXRCE_ENTITY_CREATION_DESTROY_TIMEOUT=0")
```

I will test more with these tomorrow.

**Comment by pablogs9** [comment]
Yes, it shall be done using the colcon meta and [rebuilding the library](https://github.com/micro-ROS/micro_ros_raspberrypi_pico_sdk#how-to-build-the-precompiled-library)

**Comment by monkeyiq** [comment]
The API call I was missing was `rmw_uros_set_context_entity_destroy_session_timeout()`. Adding that call makes destroy_entities happen in a reasonable amount of time. https://github.com/monkeyiq/micro_ros_raspberrypi_pico_sdk_reconnect/blob/e9a1ddecf209cd8c80620fc8b0e31f7de7fb55c7/pico_micro_ros_example.c#L87

I had experimented with lowering the ping times a little as shown in the example I have based on the above linked code and the example in this repository: https://github.com/monkeyiq/micro_ros_raspberrypi_pico_sdk_reconnect/blob/humble/pico_micro_ros_example.c

IMHO it is a bit of a race condition on the first `rmw_uros_ping_agent()` call done after `create_entities()`. I have a relay controller which has 9 pubs and subs (recompiled microros to allow this). On that and a 50ms initial ping timeout I was seeing some dropouts on initial connection. Going back to the 100ms as shown in https://github.com/micro-ROS/micro_ros_arduino/blob/humble/examples/micro-ros_reconnection_example/micro-ros_reconnection_example.ino removed those drop outs. Though if there is significant IO started in `create_entities()` then 100ms might not always be enough. With this in mind I added a CONNECTING state to allow longer initial timeouts on the first ping to my example https://github.com/monkeyiq/micro_ros_raspberrypi_pico_sdk_reconnect/blob/e9a1ddecf209cd8c80620fc8b0e31f7de7fb55c7/pico_micro_ros_example.c#L116

Maybe the CONNECTING state could try work out how much data is still on the wire before attempting a ping().

I also have code using the heartbeat sub and timer which avoids having to do any ping in the connected state as it relies on these ROS messages getting through to detect a stale or closed connection. Happy to share an example of that too if it might be of use.

The example [1] I created for testing uses 3-5 LEDs to show state. Without a connection to an agent the red LED blinks and the green and blue LEDs are on. When there is an agent connection the red LED is solid on and the green LED blinks a little (mostly off) and blue are all on. When the `destroy_entities` is called blue LEDs turn off in succession. This last part can not really be seen with 0 timeout in `rmw_uros_set_context_entity_destroy_session_timeout(rmw_context, 0);` because it is too quick.

[1] https://github.com/monkeyiq/micro_ros_raspberrypi_pico_sdk_reconnect/blob/humble/pico_micro_ros_example.c
