### ISSUE TITLE
where is microros in CMakeLists.txt

### ISSUE THREAD

**Issue by tianrking** [micro-ROS/micro_ros_raspberrypi_pico_sdk#716]
I would like to know which is the corresponding file for this.  I could not find it.

libraries microros  in below code 

```c++
target_link_libraries(pico_micro_ros_example
    pico_stdlib
    microros
)
```

pico_stdlib is in pico_sdk/src/common/ but where is microros

**Comment by tianrking** [comment]
@pablogs9 thanks for your reply. but I dont understand why cannot write like this

```c++
target_link_libraries(pico_micro_ros_example
    pico_stdlib
    libmicroros
)
```

why microros instead of libmicroros .
and in libmicroros DIR i cant find something like microros.xxx

**Comment by pablogs9** [comment]
https://stackoverflow.com/questions/6561273/is-liblibrary-name-a-so-a-naming-convention-for-static-libraries-in-linux
