### ISSUE TITLE
Contributing with support for pico w

### ISSUE THREAD

**Issue by taall973** [micro-ROS/micro_ros_raspberrypi_pico_sdk#889]
Hello, until last month I worked with uros with my classmates. We have developed an implementation for pico w board. We would like to contribute if possible but I don't know how to do it. Where should we start? The code is currently accessible at [this repo](https://github.com/PICO-MAZING/uros_pico_w) still with debug but it works.

**Comment by pablogs9** [comment]
Hi, could you open a PR with your changes to this repo?

**Comment by taall973** [comment]
Ok I'll try this.

**Comment by taall973** [comment]
Done
