### ISSUE TITLE
[Suggestion]: Add simpler static library builder

### ISSUE THREAD

**Issue by holmbuar** [micro-ROS/micro_ros_raspberrypi_pico_sdk#947]
The current version of the Docker image `micro_ros_static_library_builder`, in combination with the [shell script](https://github.com/micro-ROS/micro_ros_raspberrypi_pico_sdk/blob/iron/microros_static_library/library_generation/library_generation.sh), could work better in my project.

For example, it deletes CMake files from all `src` subfolders (my custom libraries)

I would like to discuss a modified shell script, in order to only install extra packages, not affecting existing structure.

**Comment by pablogs9** [comment]
Hello @torlarse, please feel free to contribute to this repo via Github Pull Requests, if you need any support, we can discuss on top of your proposal in the actual PR.
