### ISSUE TITLE
Custom interface not working

### ISSUE THREAD

**Issue by holmbuar** [micro-ROS/micro_ros_raspberrypi_pico_sdk#948]
I'm not sure if my custom service from https://github.com/micro-ROS/micro_ros_raspberrypi_pico_sdk/issues/945 actually works, since it shows up in

```
$ ros2 service type /motor_data

custom_interfaces/srv/MotorData
```
but not in

```
$ ros2 interface list
```
or

```
$ ros2 interface show custom_interfaces/srv/MotorData

Unknown package 'custom_interfaces'
```
I've tried a lot of combinations of the  service call commands, like
```
$ ros2 service call /motor_data custom_interfaces/srv/MotorData "{send: 1}"

The passed service type is invalid
```
srv/MotorData.srv:
```
int32 send
---
float64 left_velocity
float64 left_position
float64 right_velocity
float64 right_position
```

Sorry for spamming. I could ask in ROS questions, but since the package install procedure is not "normal", I prefer to check here first.

**Comment by pablogs9** [comment]
Have you installed your custom message in the ROS 2 side? This `custom_interfaces/srv/MotorData` seems to be not installed in or sourced in your ROS2 CLI

**Comment by holmbuar** [comment]
I had not installed custom message on ROS2 side. Thanks!
